abstract: Perl extension to OpenSSL's PKCS12 API.
author: 'Dan Sully, <daniel@cpan.org>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Crypt-OpenSSL-PKCS12
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
version: 0.3
