---
abstract: "Perl extension to OpenSSL's PKCS12 API."
author:
  - 'Dan Sully, <daniel@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Pod::Coverage: 0.19
  Test::More: 0.47
  Test::Pod::Coverage: 1.08
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenSSL-PKCS12
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
resources:
  bugtracker: https://github.com/dsully/perl-crypt-openssl-pkcs12/issues
  homepage: https://github.com/dsully/perl-crypt-openssl-pkcs12
  license: http://dev.perl.org/licenses/
version: 0.6
